export const GameLibrary = [{
  name: 'risk',
  displayName: 'Risk',
  numberOfPlayers: 6,
  tokens: ['black', 'blue', 'red', 'green', 'yellow', 'purple'],
  turnOrderMethod: 'set once',
  available: true,
  accessibleForKids: true,
  longGame: false,
  cooperative: false,
  description: 'Individual players fight for global conquest.',
}, {
  name: 'axisAndAlliesWW2',
  displayName: 'Axis and Allies WW2',
  numberOfPlayers: 5,
  tokens: ['U.S', 'Great Britain', 'Russia', 'Germany', 'Japan'],
  turnOrderMethod: 'preset',
  available: false,
  accessibleForKids: true,
  longGame: false,
  cooperative: false,
  description: 'A historical game based on World War 2. The Axis and the Allied teams battle for victory by conquring competing areas or by building a strong enough economy.',
}, {
  name: 'firefly',
  displayName: 'Firefly',
  numberOfPlayers: 4,
  tokens: ['orange', 'yellow', 'blue', 'green'],
  turnOrderMethod: 'set once',
  available: false,
  accessibleForKids: false,
  longGame: true,
  cooperative: false,
  description: 'A game based on the cult favorite Firefly by Joss Wheadon. Individual players travel across the \'verse\' and complete jobs for crime bosses to help them meet goals for the selected mission.',
}];
